#include <delta/protocol/get_config.hpp>
#include <delta/protocol/config.hpp>
#include <delta/protocol/asset.hpp>
#include <delta/protocol/types.hpp>
#include <delta/protocol/version.hpp>

namespace delta { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef DELTA_ENABLE_SMT
   result[ "DELTA_ENABLE_SMT" ] = true;
   result["SMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = SMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
#else
   result[ "DELTA_ENABLE_SMT" ] = false;
#endif

   result["DBD_SYMBOL"] = DBD_SYMBOL;
   result["DELTA_INITIAL_VOTE_POWER_RATE"] = DELTA_INITIAL_VOTE_POWER_RATE;
   result["DELTA_REDUCED_VOTE_POWER_RATE"] = DELTA_REDUCED_VOTE_POWER_RATE;
   result["DELTA_100_PERCENT"] = DELTA_100_PERCENT;
   result["DELTA_1_PERCENT"] = DELTA_1_PERCENT;
   result["DELTA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = DELTA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["DELTA_ACTIVE_CHALLENGE_COOLDOWN"] = DELTA_ACTIVE_CHALLENGE_COOLDOWN;
   result["DELTA_ACTIVE_CHALLENGE_FEE"] = DELTA_ACTIVE_CHALLENGE_FEE;
   result["DELTA_ADDRESS_PREFIX"] = DELTA_ADDRESS_PREFIX;
   result["DELTA_APR_PERCENT_MULTIPLY_PER_BLOCK"] = DELTA_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["DELTA_APR_PERCENT_MULTIPLY_PER_HOUR"] = DELTA_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["DELTA_APR_PERCENT_MULTIPLY_PER_ROUND"] = DELTA_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["DELTA_APR_PERCENT_SHIFT_PER_BLOCK"] = DELTA_APR_PERCENT_SHIFT_PER_BLOCK;
   result["DELTA_APR_PERCENT_SHIFT_PER_HOUR"] = DELTA_APR_PERCENT_SHIFT_PER_HOUR;
   result["DELTA_APR_PERCENT_SHIFT_PER_ROUND"] = DELTA_APR_PERCENT_SHIFT_PER_ROUND;
   result["DELTA_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = DELTA_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["DELTA_BANDWIDTH_PRECISION"] = DELTA_BANDWIDTH_PRECISION;
   result["DELTA_BLOCKCHAIN_PRECISION"] = DELTA_BLOCKCHAIN_PRECISION;
   result["DELTA_BLOCKCHAIN_PRECISION_DIGITS"] = DELTA_BLOCKCHAIN_PRECISION_DIGITS;
   result["DELTA_BLOCKCHAIN_HARDFORK_VERSION"] = DELTA_BLOCKCHAIN_HARDFORK_VERSION;
   result["DELTA_BLOCKCHAIN_VERSION"] = DELTA_BLOCKCHAIN_VERSION;
   result["DELTA_BLOCK_INTERVAL"] = DELTA_BLOCK_INTERVAL;
   result["DELTA_BLOCKS_PER_DAY"] = DELTA_BLOCKS_PER_DAY;
   result["DELTA_BLOCKS_PER_HOUR"] = DELTA_BLOCKS_PER_HOUR;
   result["DELTA_BLOCKS_PER_YEAR"] = DELTA_BLOCKS_PER_YEAR;
   result["DELTA_CASHOUT_WINDOW_SECONDS"] = DELTA_CASHOUT_WINDOW_SECONDS;
   result["DELTA_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = DELTA_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["DELTA_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = DELTA_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["DELTA_CHAIN_ID"] = DELTA_CHAIN_ID;
   result["DELTA_COMMENT_REWARD_FUND_NAME"] = DELTA_COMMENT_REWARD_FUND_NAME;
   result["DELTA_CONTENT_APR_PERCENT"] = DELTA_CONTENT_APR_PERCENT;
   result["DELTA_CONTENT_CONSTANT_HF0"] = DELTA_CONTENT_CONSTANT_HF0;
   result["DELTA_CONTENT_REWARD_PERCENT"] = DELTA_CONTENT_REWARD_PERCENT;
   result["DELTA_CONVERSION_DELAY"] = DELTA_CONVERSION_DELAY;
   result["DELTA_CONVERSION_DELAY_PRE_HF_16"] = DELTA_CONVERSION_DELAY_PRE_HF_16;
   result["DELTA_CREATE_ACCOUNT_DELEGATION_RATIO"] = DELTA_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["DELTA_CREATE_ACCOUNT_DELEGATION_TIME"] = DELTA_CREATE_ACCOUNT_DELEGATION_TIME;
   result["DELTA_CREATE_ACCOUNT_WITH_DELTA_MODIFIER"] = DELTA_CREATE_ACCOUNT_WITH_DELTA_MODIFIER;
   result["DELTA_CURATE_APR_PERCENT"] = DELTA_CURATE_APR_PERCENT;
   result["DELTA_DEFAULT_DBD_INTEREST_RATE"] = DELTA_DEFAULT_DBD_INTEREST_RATE;
   result["DELTA_EQUIHASH_K"] = DELTA_EQUIHASH_K;
   result["DELTA_EQUIHASH_N"] = DELTA_EQUIHASH_N;
   result["DELTA_FEED_HISTORY_WINDOW"] = DELTA_FEED_HISTORY_WINDOW;
   result["DELTA_FEED_HISTORY_WINDOW_PRE_HF_16"] = DELTA_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["DELTA_FEED_INTERVAL_BLOCKS"] = DELTA_FEED_INTERVAL_BLOCKS;
   result["DELTA_GENESIS_TIME"] = DELTA_GENESIS_TIME;
   result["DELTA_HARDFORK_REQUIRED_WITNESSES"] = DELTA_HARDFORK_REQUIRED_WITNESSES;
   result["DELTA_INFLATION_NARROWING_PERIOD"] = DELTA_INFLATION_NARROWING_PERIOD;
   result["DELTA_INFLATION_RATE_START_PERCENT"] = DELTA_INFLATION_RATE_START_PERCENT;
   result["DELTA_INFLATION_RATE_STOP_PERCENT"] = DELTA_INFLATION_RATE_STOP_PERCENT;
   result["DELTA_INIT_MINER_NAME"] = DELTA_INIT_MINER_NAME;
   result["DELTA_INIT_PUBLIC_KEY_STR"] = DELTA_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["DELTA_INIT_PRIVATE_KEY"] = DELTA_INIT_PRIVATE_KEY;
#endif
   result["DELTA_INIT_SUPPLY"] = DELTA_INIT_SUPPLY;
   result["DELTA_INIT_TIME"] = DELTA_INIT_TIME;
   result["DELTA_IRREVERSIBLE_THRESHOLD"] = DELTA_IRREVERSIBLE_THRESHOLD;
   result["DELTA_LIQUIDITY_APR_PERCENT"] = DELTA_LIQUIDITY_APR_PERCENT;
   result["DELTA_LIQUIDITY_REWARD_BLOCKS"] = DELTA_LIQUIDITY_REWARD_BLOCKS;
   result["DELTA_LIQUIDITY_REWARD_PERIOD_SEC"] = DELTA_LIQUIDITY_REWARD_PERIOD_SEC;
   result["DELTA_LIQUIDITY_TIMEOUT_SEC"] = DELTA_LIQUIDITY_TIMEOUT_SEC;
   result["DELTA_MAX_ACCOUNT_CREATION_FEE"] = DELTA_MAX_ACCOUNT_CREATION_FEE;
   result["DELTA_MAX_ACCOUNT_NAME_LENGTH"] = DELTA_MAX_ACCOUNT_NAME_LENGTH;
   result["DELTA_MAX_ACCOUNT_WITNESS_VOTES"] = DELTA_MAX_ACCOUNT_WITNESS_VOTES;
   result["DELTA_MAX_ASSET_WHITELIST_AUTHORITIES"] = DELTA_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["DELTA_MAX_AUTHORITY_MEMBERSHIP"] = DELTA_MAX_AUTHORITY_MEMBERSHIP;
   result["DELTA_MAX_BLOCK_SIZE"] = DELTA_MAX_BLOCK_SIZE;
   result["DELTA_SOFT_MAX_BLOCK_SIZE"] = DELTA_SOFT_MAX_BLOCK_SIZE;
   result["DELTA_MAX_CASHOUT_WINDOW_SECONDS"] = DELTA_MAX_CASHOUT_WINDOW_SECONDS;
   result["DELTA_MAX_COMMENT_DEPTH"] = DELTA_MAX_COMMENT_DEPTH;
   result["DELTA_MAX_COMMENT_DEPTH_PRE_HF17"] = DELTA_MAX_COMMENT_DEPTH_PRE_HF17;
   result["DELTA_MAX_FEED_AGE_SECONDS"] = DELTA_MAX_FEED_AGE_SECONDS;
   result["DELTA_MAX_INSTANCE_ID"] = DELTA_MAX_INSTANCE_ID;
   result["DELTA_MAX_MEMO_SIZE"] = DELTA_MAX_MEMO_SIZE;
   result["DELTA_MAX_WITNESSES"] = DELTA_MAX_WITNESSES;
   result["DELTA_MAX_MINER_WITNESSES_HF0"] = DELTA_MAX_MINER_WITNESSES_HF0;
   result["DELTA_MAX_MINER_WITNESSES_HF17"] = DELTA_MAX_MINER_WITNESSES_HF17;
   result["DELTA_MAX_PERMLINK_LENGTH"] = DELTA_MAX_PERMLINK_LENGTH;
   result["DELTA_MAX_PROXY_RECURSION_DEPTH"] = DELTA_MAX_PROXY_RECURSION_DEPTH;
   result["DELTA_MAX_RATION_DECAY_RATE"] = DELTA_MAX_RATION_DECAY_RATE;
   result["DELTA_MAX_RESERVE_RATIO"] = DELTA_MAX_RESERVE_RATIO;
   result["DELTA_MAX_RUNNER_WITNESSES_HF0"] = DELTA_MAX_RUNNER_WITNESSES_HF0;
   result["DELTA_MAX_RUNNER_WITNESSES_HF17"] = DELTA_MAX_RUNNER_WITNESSES_HF17;
   result["DELTA_MAX_SATOSHIS"] = DELTA_MAX_SATOSHIS;
   result["DELTA_MAX_SHARE_SUPPLY"] = DELTA_MAX_SHARE_SUPPLY;
   result["DELTA_MAX_SIG_CHECK_DEPTH"] = DELTA_MAX_SIG_CHECK_DEPTH;
   result["DELTA_MAX_SIG_CHECK_ACCOUNTS"] = DELTA_MAX_SIG_CHECK_ACCOUNTS;
   result["DELTA_MAX_TIME_UNTIL_EXPIRATION"] = DELTA_MAX_TIME_UNTIL_EXPIRATION;
   result["DELTA_MAX_TRANSACTION_SIZE"] = DELTA_MAX_TRANSACTION_SIZE;
   result["DELTA_MAX_UNDO_HISTORY"] = DELTA_MAX_UNDO_HISTORY;
   result["DELTA_MAX_URL_LENGTH"] = DELTA_MAX_URL_LENGTH;
   result["DELTA_MAX_VOTE_CHANGES"] = DELTA_MAX_VOTE_CHANGES;
   result["DELTA_MAX_VOTED_WITNESSES_HF0"] = DELTA_MAX_VOTED_WITNESSES_HF0;
   result["DELTA_MAX_VOTED_WITNESSES_HF17"] = DELTA_MAX_VOTED_WITNESSES_HF17;
   result["DELTA_MAX_WITHDRAW_ROUTES"] = DELTA_MAX_WITHDRAW_ROUTES;
   result["DELTA_MAX_WITNESS_URL_LENGTH"] = DELTA_MAX_WITNESS_URL_LENGTH;
   result["DELTA_MIN_ACCOUNT_CREATION_FEE"] = DELTA_MIN_ACCOUNT_CREATION_FEE;
   result["DELTA_MIN_ACCOUNT_NAME_LENGTH"] = DELTA_MIN_ACCOUNT_NAME_LENGTH;
   result["DELTA_MIN_BLOCK_SIZE_LIMIT"] = DELTA_MIN_BLOCK_SIZE_LIMIT;
   result["DELTA_MIN_BLOCK_SIZE"] = DELTA_MIN_BLOCK_SIZE;
   result["DELTA_MIN_CONTENT_REWARD"] = DELTA_MIN_CONTENT_REWARD;
   result["DELTA_MIN_CURATE_REWARD"] = DELTA_MIN_CURATE_REWARD;
   result["DELTA_MIN_PERMLINK_LENGTH"] = DELTA_MIN_PERMLINK_LENGTH;
   result["DELTA_MIN_REPLY_INTERVAL"] = DELTA_MIN_REPLY_INTERVAL;
   result["DELTA_MIN_REPLY_INTERVAL_HF20"] = DELTA_MIN_REPLY_INTERVAL_HF20;
   result["DELTA_MIN_ROOT_COMMENT_INTERVAL"] = DELTA_MIN_ROOT_COMMENT_INTERVAL;
   result["DELTA_MIN_VOTE_INTERVAL_SEC"] = DELTA_MIN_VOTE_INTERVAL_SEC;
   result["DELTA_MINER_ACCOUNT"] = DELTA_MINER_ACCOUNT;
   result["DELTA_MINER_PAY_PERCENT"] = DELTA_MINER_PAY_PERCENT;
   result["DELTA_MIN_FEEDS"] = DELTA_MIN_FEEDS;
   result["DELTA_MINING_REWARD"] = DELTA_MINING_REWARD;
   result["DELTA_MINING_TIME"] = DELTA_MINING_TIME;
   result["DELTA_MIN_LIQUIDITY_REWARD"] = DELTA_MIN_LIQUIDITY_REWARD;
   result["DELTA_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = DELTA_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["DELTA_MIN_PAYOUT_DBD"] = DELTA_MIN_PAYOUT_DBD;
   result["DELTA_MIN_POW_REWARD"] = DELTA_MIN_POW_REWARD;
   result["DELTA_MIN_PRODUCER_REWARD"] = DELTA_MIN_PRODUCER_REWARD;
   result["DELTA_MIN_TRANSACTION_EXPIRATION_LIMIT"] = DELTA_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["DELTA_MIN_TRANSACTION_SIZE_LIMIT"] = DELTA_MIN_TRANSACTION_SIZE_LIMIT;
   result["DELTA_MIN_UNDO_HISTORY"] = DELTA_MIN_UNDO_HISTORY;
   result["DELTA_NULL_ACCOUNT"] = DELTA_NULL_ACCOUNT;
   result["DELTA_NUM_INIT_MINERS"] = DELTA_NUM_INIT_MINERS;
   result["DELTA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = DELTA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["DELTA_OWNER_AUTH_RECOVERY_PERIOD"] = DELTA_OWNER_AUTH_RECOVERY_PERIOD;
   result["DELTA_OWNER_CHALLENGE_COOLDOWN"] = DELTA_OWNER_CHALLENGE_COOLDOWN;
   result["DELTA_OWNER_CHALLENGE_FEE"] = DELTA_OWNER_CHALLENGE_FEE;
   result["DELTA_OWNER_UPDATE_LIMIT"] = DELTA_OWNER_UPDATE_LIMIT;
   result["DELTA_POST_AVERAGE_WINDOW"] = DELTA_POST_AVERAGE_WINDOW;
   result["DELTA_POST_REWARD_FUND_NAME"] = DELTA_POST_REWARD_FUND_NAME;
   result["DELTA_POST_WEIGHT_CONSTANT"] = DELTA_POST_WEIGHT_CONSTANT;
   result["DELTA_POW_APR_PERCENT"] = DELTA_POW_APR_PERCENT;
   result["DELTA_PRODUCER_APR_PERCENT"] = DELTA_PRODUCER_APR_PERCENT;
   result["DELTA_PROXY_TO_SELF_ACCOUNT"] = DELTA_PROXY_TO_SELF_ACCOUNT;
   result["DELTA_DBD_INTEREST_COMPOUND_INTERVAL_SEC"] = DELTA_DBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["DELTA_SECONDS_PER_YEAR"] = DELTA_SECONDS_PER_YEAR;
   result["DELTA_RECENT_RSHARES_DECAY_TIME_HF19"] = DELTA_RECENT_RSHARES_DECAY_TIME_HF19;
   result["DELTA_RECENT_RSHARES_DECAY_TIME_HF17"] = DELTA_RECENT_RSHARES_DECAY_TIME_HF17;
   result["DELTA_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = DELTA_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["DELTA_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = DELTA_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["DELTA_ROOT_POST_PARENT"] = DELTA_ROOT_POST_PARENT;
   result["DELTA_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = DELTA_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["DELTA_SAVINGS_WITHDRAW_TIME"] = DELTA_SAVINGS_WITHDRAW_TIME;
   result["DELTA_DBD_START_PERCENT_HF14"] = DELTA_DBD_START_PERCENT_HF14;
   result["DELTA_DBD_START_PERCENT_HF20"] = DELTA_DBD_START_PERCENT_HF20;
   result["DELTA_DBD_STOP_PERCENT_HF14"] = DELTA_DBD_STOP_PERCENT_HF14;
   result["DELTA_DBD_STOP_PERCENT_HF20"] = DELTA_DBD_STOP_PERCENT_HF20;
   result["DELTA_SECOND_CASHOUT_WINDOW"] = DELTA_SECOND_CASHOUT_WINDOW;
   result["DELTA_SOFT_MAX_COMMENT_DEPTH"] = DELTA_SOFT_MAX_COMMENT_DEPTH;
   result["DELTA_START_MINER_VOTING_BLOCK"] = DELTA_START_MINER_VOTING_BLOCK;
   result["DELTA_START_VESTING_BLOCK"] = DELTA_START_VESTING_BLOCK;
   result["DELTA_TEMP_ACCOUNT"] = DELTA_TEMP_ACCOUNT;
   result["DELTA_UPVOTE_LOCKOUT_HF7"] = DELTA_UPVOTE_LOCKOUT_HF7;
   result["DELTA_UPVOTE_LOCKOUT_HF17"] = DELTA_UPVOTE_LOCKOUT_HF17;
   result["DELTA_UPVOTE_LOCKOUT_SECONDS"] = DELTA_UPVOTE_LOCKOUT_SECONDS;
   result["DELTA_VESTING_FUND_PERCENT"] = DELTA_VESTING_FUND_PERCENT;
   result["DELTA_VESTING_WITHDRAW_INTERVALS"] = DELTA_VESTING_WITHDRAW_INTERVALS;
   result["DELTA_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = DELTA_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["DELTA_VESTING_WITHDRAW_INTERVAL_SECONDS"] = DELTA_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["DELTA_VOTE_DUST_THRESHOLD"] = DELTA_VOTE_DUST_THRESHOLD;
   result["DELTA_VOTING_MANA_REGENERATION_SECONDS"] = DELTA_VOTING_MANA_REGENERATION_SECONDS;
   result["DELTA_SYMBOL"] = DELTA_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["DELTA_VIRTUAL_SCHEDULE_LAP_LENGTH"] = DELTA_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["DELTA_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = DELTA_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["DELTA_MAX_LIMIT_ORDER_EXPIRATION"] = DELTA_MAX_LIMIT_ORDER_EXPIRATION;
   result["DELTA_DELEGATION_RETURN_PERIOD_HF0"] = DELTA_DELEGATION_RETURN_PERIOD_HF0;
   result["DELTA_DELEGATION_RETURN_PERIOD_HF20"] = DELTA_DELEGATION_RETURN_PERIOD_HF20;
   result["DELTA_RD_MIN_DECAY_BITS"] = DELTA_RD_MIN_DECAY_BITS;
   result["DELTA_RD_MAX_DECAY_BITS"] = DELTA_RD_MAX_DECAY_BITS;
   result["DELTA_RD_DECAY_DENOM_SHIFT"] = DELTA_RD_DECAY_DENOM_SHIFT;
   result["DELTA_RD_MAX_POOL_BITS"] = DELTA_RD_MAX_POOL_BITS;
   result["DELTA_RD_MAX_BUDGET_1"] = DELTA_RD_MAX_BUDGET_1;
   result["DELTA_RD_MAX_BUDGET_2"] = DELTA_RD_MAX_BUDGET_2;
   result["DELTA_RD_MAX_BUDGET_3"] = DELTA_RD_MAX_BUDGET_3;
   result["DELTA_RD_MAX_BUDGET"] = DELTA_RD_MAX_BUDGET;
   result["DELTA_RD_MIN_DECAY"] = DELTA_RD_MIN_DECAY;
   result["DELTA_RD_MIN_BUDGET"] = DELTA_RD_MIN_BUDGET;
   result["DELTA_RD_MAX_DECAY"] = DELTA_RD_MAX_DECAY;
   result["DELTA_ACCOUNT_SUBSIDY_PRECISION"] = DELTA_ACCOUNT_SUBSIDY_PRECISION;
   result["DELTA_WITNESS_SUBSIDY_BUDGET_PERCENT"] = DELTA_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["DELTA_WITNESS_SUBSIDY_DECAY_PERCENT"] = DELTA_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["DELTA_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = DELTA_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["DELTA_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = DELTA_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["DELTA_DECAY_BACKSTOP_PERCENT"] = DELTA_DECAY_BACKSTOP_PERCENT;

   return result;
}

} } // delta::protocol
